### ISSUE TITLE
NoMethodError (undefined method `post' for nil:NilClass)

### ISSUE THREAD

**Issue by ihenvyr** [podio/podio-rb#15]
Hello,

"NoMethodError (undefined method `post' for nil:NilClass)" shows only in production when the app executes Podio::Item.create, Podio::Search.in_app, etc. I tried to execute the same thing in the production console but it works. Same goes under development environment - the app works fine. My current setup below:

config/initializers/podio.rb
require 'rubygems'
require 'podio'
Podio.setup(:api_key => 'YOUR_API_KEY', :api_secret => 'YOUR_API_SECRET')
Podio.client.authenticate_with_credentials('YOUR_PODIO_ACCOUNT', 'YOUR_PODIO_PASSWORD')

Thanks,

Henry

**Comment by jclay** [comment]
Just ran into this issue as well. Thanks for the workaround @danmaz74

**Comment by f6v** [comment]
Having the same issue when calling Podio in Sidekiq job. What's the best way to initialise library when using Sidekiq?

**Comment by cpeters** [comment]
I haven't personally used Sidekiq but I did a quick scan of the docs. There is a mention that workers must be thread safe. It appears that you'd have to initialize a connection to the Podio Api within each worker.
