### ISSUE TITLE
getting bitten by uninitialized constant ActiveSupport::Autoload

### ISSUE THREAD

**Issue by cixelsyd** [podio/podio-rb#16]
Hi.  Please see:
https://github.com/rails/rails/issues/14664

Your gem is impacted.  When I add require 'active_support' to ./lib/podio.rb it works well:

```
require 'faraday'
require 'active_support'
require 'active_support/core_ext'
```

Otherwise, I receive random errors on some of my machines, just as others have reported.

**Comment by jeffdeville** [comment]
@andreas This is still a problem. Please fix
