### ISSUE TITLE
ItemDiff.revert used inside hook causes infinite loop

### ISSUE THREAD

**Issue by homeofmatt** [podio/podio-rb#27]
When a user updates a field on an item in Podio, an update hook is triggered in my app. Thing is, there are a couple fields that I don't want changed at all. Since there's no read-only option per field, I'm trying to use the revert function, but it constantly throws an infinite loop. Is there any way to prevent this? 
I'm using Ruby.

ex: 
when 'item.update'
    (setup code)
    if label == 'Project'
        Podio::ItemDiff.revert(@item_id, @curr_rev)
    end
end

**Comment by homeofmatt** [comment]
Edit: I've scoured the code in this repo and it seems like the model "connection" might have what I need, but I can't find it in the models folder even though it's autoloaded (podio/models/connection) in podio.rb

**Comment by RSpace** [comment]
Reverting an item revision also triggers the update web hook, as it should. It's up to you to write your code so it knows not to react to the second call from the update web hook, thereby preventing the a loop. 

Please ask further questions here: https://help.podio.com/hc/communities/public/topics/200069178-3-Podio-API-developer-forum
