### ISSUE TITLE
Versioning and Tagging?

### ISSUE THREAD

**Issue by jhirbour** [podio/podio-rb#31]
You've stated that you follow semantic versioning, but it seems like it's been a long while since a tag has been added to this repo. We use this gem in our app and need to pin a specific version. We'd prefer to use a tag rather than a SHA.

**Comment by jhirbour** [comment]
cc: @alexwilkinson

**Comment by florish** [comment]
Updating the version (and git tag) more frequently would have been a time saver for me, too. Yook me a while to figure out I had to put a direct link to the GitHub repository in my `Gemfile` to get a working version of the gem.

**Comment by dominicsayers** [comment]
I want to add this gem as a runtime dependency in my own gem, but that's impossible at the moment because the version in Rubygems is out of date.

Please release 0.1.0 in the normal way.

**Comment by theflow** [comment]
I pushed a new version now

**Comment by dominicsayers** [comment]
:tada:
