### ISSUE TITLE
Rate limit information

### ISSUE THREAD

**Issue by dominicsayers** [podio/podio-rb#37]
I'm currently running into API rate limits during testing of my app. It would be really cool to be able to interrogate the Podio object for information about how many calls are left for a given API endpoint.

I believe this information could be gathered from the response headers as explained here: https://developers.podio.com/index/limits

**Comment by dominicsayers** [comment]
Bump

**Comment by dmatteo** [comment]
Hi Dominic,

as you pointed out, you can get the remaining calls from the headers of the last API call you made, but we don't offer any other way of retrieving the remaining API calls left.

Unfortunately we also don't offer a "timer" for when your call limit will be reset (e.g. the hour limit)

**Comment by dominicsayers** [comment]
My point was: if you are using the gem you don't have access to the raw headers so you can't get at the rate limit usage.

So...it would be good if the Podio object exposed it.
