### ISSUE TITLE
External id not returned by "Get item revision difference"

### ISSUE THREAD

**Issue by dominicsayers** [podio/podio-rb#39]
In [item_diff.rb](https://github.com/podio/podio-rb/blob/master/lib/podio/models/item_diff.rb#L5) a property called `external_id` is defined.

This property is never populated by the [underlying API](https://developers.podio.com/doc/items/get-item-revision-difference-22374)

I believe this property is useful and *should* be populated. Can the underlying API be enhanced to include this property?

**Comment by cpeters** [comment]
There is an `external_id` on an `item` and `item_field`. There is no `external_id` on an `item_diff`. This property appears to have been added to the `item_diff` model by mistake. There is no use case for referencing an `item_diff` with an `external_id`. The diff of an `item` is generated during an API call and never persisted. You cannot reference an `item_diff` with an `external_id`

There will be a fix to the library.

Thanks for pointing out the issue.

**Comment by dominicsayers** [comment]
Just seems odd that the `label` is populated but the `external_id` isn't. Seems a bit arbitrary to populate one and not the other.

I have used the `external_id` in my app to associate Podio fields with my app's fields. I chose `external_id` because it was more human-readable than the `field_id`. It works well with every API call except this one.

**Comment by cpeters** [comment]
I think what you are asking for is not an `external_id` of an `item_diff` object; but an `external_id` of each `field` returned in the `item_diff` query response. Is that correct?

**Comment by dominicsayers** [comment]
@cpeters sorry if I wasn't clear! I should have been more careful in my original description. Yes, you are quite correct; I believe the `external_id` could usefully be included for each changed field in the diff.

**Comment by cpeters** [comment]
@dominicsayers Thank you for the feedback regarding the API. I have added a feature request to include the `external_id` of each `field` returned when querying an `item_diff`

**Comment by cpeters** [comment]
@dominicsayers The API has been updated to include the `external_id` of each `field` returned in an `item_diff` query. If you run into any issues please reach out to us.

**Comment by dominicsayers** [comment]
Just checked it. That's awesome, @cpeters. Thank you!

**Comment by dominicsayers** [comment]
The only other thing you could do is update the [excellent documentation](https://developers.podio.com/doc/items/get-item-revision-difference-22374) to reflect the changed format of the returned data. Just a suggestion.

**Comment by cpeters** [comment]
Documentation will be updated. Thanks @dominicsayers
