### ISSUE TITLE
Podio API & gem still alive?

### ISSUE THREAD

**Issue by dominicsayers** [podio/podio-rb#40]
I'm trying to write code using the Podio API and this gem, but I'm finding it difficult to get a response from Podio/Cisco developers.

Questions on StackOverflow are answered by inexperienced staff if at all.

Issues raised here are ignored.

I don't think my questions or suggestions are unreasonable and it's difficult to contemplate continuing to use Podio if the API is a stale project unsupported by Cisco.

@theflow @RSpace: Sorry to bug you but do you know of anybody I can contact to find out whether the API is still supported by Cisco?

**Comment by cpeters** [comment]
For clarification, Podio is a product of Citrix; not Cisco.

To answer your question, yes, we are actively developing the API and maintaining the various language clients.
