### ISSUE TITLE
Outdated Faraday dependency

### ISSUE THREAD

**Issue by dukeimg** [podio/podio-rb#48]
Hi. Hope you're doing great!

In the project you have a dependency:

    s.add_dependency('faraday', ['>= 0.8.0', '< 0.10.0'])

And I want to use `podio-rb` along with another gem that requires Faraday `>= 0.12.0`.

Do you have any plans on upgrading Faraday dependency?

**Comment by cpeters** [comment]
Use bundler.

http://bundler.io/gemfile.html

**Comment by dukeimg** [comment]
It won't work for me because I will have to include 2 different versions of Faraday to my Rails project the same time :D

**Comment by cpeters** [comment]
That's exactly why you use bundler.

**Comment by DevvViktor** [comment]
I apologize, I forgot to mention that `gem 'faraday', '~> 0.12.0.1'` is also required in `Gemfile` because it is directly used in the project for some requests. So I can't really resolve this dependency issue.

```
Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    faraday (~> 0.12.0.1)

    podio (>= 2.0.0) was resolved to 2.0.0, which depends on
      faraday (< 0.10.0, >= 0.8.0)
```

**Comment by dukeimg** [comment]
I apologize, I forgot to mention that `gem 'faraday', '~> 0.12.0.1'` is also required in `Gemfile` because it is directly used in the project for some requests. So I can't really resolve this dependency issue.

```
Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    faraday (~> 0.12.0.1)

    podio (>= 2.0.0) was resolved to 2.0.0, which depends on
      faraday (< 0.10.0, >= 0.8.0)
```

**Comment by cpeters** [comment]
I see. We don't currently have any plans to upgrade faraday. If you'd like to do the upgrade and create a pull request I will gladly review it and release an update to the podio gem.

**Comment by dukeimg** [comment]
Well, I tried to upgrade dependency today and it seem that `podio-rb` still passes all tests. I make a pull request then.
